POCONC-145: Add INR, LCC and RCC to flat_vitals table
AMPATH/ng2-amrs pull request #1103
Opened 2019-07-10 11:31 UTC by denniskigen

This commit adds logic for displaying International Normalized Ratio (INR), Left Calf Circumference (cm) and Right Calf Circumference (cm) in the vitals table for Anticoagulation Treatment patients.

2019-07-15 08:40 UTC, drizzentic submitted a review, later dismissed

2019-07-31 08:38 UTC, webtrendzs submitted a review, later dismissed

2019-07-31 09:06 UTC, drizzentic requested changes

2019-07-31 09:06 UTC, drizzentic commented on src/app/patient-dashboard/common/patient-vitals/patient-vitals.component.html
> +    <!-- <div [ngBusy]="{busy:loadingVitals,message:'Please Wait...'}"></div> -->
```suggestion
   
```

2019-07-31 09:06 UTC, drizzentic commented on src/app/patient-dashboard/common/patient-vitals/patient-vitals.component.ts
> +  public interpretEcogValuesForOncology(data: any) {
Would prefer using _.filter

2019-07-31 09:13 UTC, drizzentic approved these changes

2019-07-31 11:40 UTC, webtrendzs approved these changes

2019-07-31 11:41 UTC, merged