POCONC-161: Fixes and improvements to oncology diagnosis and medicati…
AMPATH/ng2-amrs pull request #1151
Opened 2019-11-21 05:53 UTC by denniskigen

Fixes and improvements to the oncology diagnosis and medication history displays (#1080):

- Show 'No diagnosis history records available' alert consistently when no diagnosis history records are found for an oncology patient.
- Show 'No medication change history records available' alert consistently when no medication change records are found for an oncology patient.

2019-11-22 13:20 UTC, madvincy requested changes

2019-11-22 13:20 UTC, madvincy commented on src/app/patient-dashboard/oncology/diagnosis-history/oncology-diagnosis-history.component.ts
> +      console.error('Error fetching patient: ', err);
is there a reason to have console.error

2019-11-22 13:20 UTC, madvincy commented on src/app/patient-dashboard/oncology/medication-history/oncology-medication-history.component.ts
> +      console.log(err);
same here

2019-11-22 13:20 UTC, madvincy commented on src/app/patient-dashboard/oncology/medication-history/oncology-medication-history.component.ts
> +        console.log(error);
same here

2019-11-22 13:31 UTC, madvincy reviewed
Check on the changes

2019-11-22 17:13 UTC, denniskigen commented on src/app/patient-dashboard/oncology/medication-history/oncology-medication-history.component.ts
> +        console.log(error);
Corrected.

2019-11-22 17:13 UTC, denniskigen commented on src/app/patient-dashboard/oncology/medication-history/oncology-medication-history.component.ts
> +      console.log(err);
Corrected.

2019-11-22 17:14 UTC, denniskigen commented on src/app/patient-dashboard/oncology/diagnosis-history/oncology-diagnosis-history.component.ts
> +      console.error('Error fetching patient: ', err);
No, it shouldn't be here.

2019-11-25 12:27 UTC, madvincy approved these changes

2019-11-25 12:30 UTC, maikofelix47 approved these changes

2019-11-25 12:31 UTC, merged