HIV-709: Add Family/Partner testing module to poc
AMPATH/ng2-amrs pull request #1359
Opened 2021-02-08 08:03 UTC by jecihjoy

2021-02-08 11:38 UTC, maikofelix47 approved these changes, later dismissed

2021-02-09 16:35 UTC, drizzentic requested changes

2021-02-09 16:35 UTC, drizzentic commented on src/app/hiv-care-lib/family-testing/contact-profile/contact-profile.component.ts
> +    }
Would you rather use a switch statement instead of if?

2021-02-09 16:35 UTC, drizzentic commented on src/app/hiv-care-lib/family-testing/contact-trace/add-contact-trace.component.ts
> +    const familyPartnerHistoryFormV1 = `3fbc8512-b37b-4bc2-a0f4-8d0ac7955127`;
I prefer we store this as a global variable because it's being used in different places. L127, L136

2021-02-09 16:35 UTC, drizzentic commented on src/app/hiv-care-lib/family-testing/contact-trace/edit-contact-trace.component.ts
> +        this.location.back();
use method `goback` defined in L120 or remove if it's only being used here

2021-02-09 16:35 UTC, drizzentic commented on src/app/hiv-care-lib/family-testing/contact-trace/edit-contact-trace.component.ts
> +      ).val;
What happens if `val` is undefined for L135 and L140

2021-02-09 16:35 UTC, drizzentic commented on src/app/hiv-care-lib/family-testing/family-testing-contact-list.component.ts
> +      '3fbc8512-b37b-4bc2-a0f4-8d0ac7955127';
Consider having this constant as global variables. Same for L220 and L227

2021-02-09 16:35 UTC, drizzentic commented on src/app/hiv-care-lib/family-testing/family-testing-patient-list.component.ts
> +      // this.gridOptions.groupHideOpenParents= true;
consider removing the commented code

2021-02-09 16:35 UTC, drizzentic commented on src/app/patient-dashboard/common/patient-encounters/patient-encounter-observations.component.html
>                [ngSwitch]="_obs.has_children"
Why is this code being commented?

2021-02-09 16:35 UTC, drizzentic commented on src/app/patient-dashboard/common/visit-encounters/visit-encounters-list.component.ts
> +    console.log(encounter);
consider removing this debug statement

2021-02-10 08:00 UTC, drizzentic commented on src/app/hiv-care-lib/family-testing/family-testing-patient-list.component.ts
> +      console.log(e);
Remove debug statements

2021-02-10 10:22 UTC, drizzentic approved these changes

2021-02-10 10:22 UTC, merged