NGPOC-2: Created a login component
AMPATH/ng2-amrs pull request #8
Opened 2016-10-25 13:49 UTC by vtuwei

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2016-10-25 14:04 UTC, vtuwei commented
@nkimaina please review

2016-10-25 16:06 UTC, nkimaina requested changes
We don't version external library files. Use npm to intall them.

2016-10-26 06:23 UTC, vtuwei commented
@nkimaina i have made the change

2016-10-26 07:21 UTC, nkimaina approved these changes

2016-10-26 08:28 UTC, merged